# Generated by Django 4.1.7 on 2023-04-28 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='CSA')),
            ],
            options={
                'verbose_name': 'CSA',
                'verbose_name_plural': 'CSAs',
            },
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Medical Condition')),
            ],
            options={
                'verbose_name': 'Medical Condition',
                'verbose_name_plural': 'Medical Conditions',
            },
        ),
        migrations.CreateModel(
            name='PregnancyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Pregnancy Category')),
            ],
            options={
                'verbose_name': 'Pregnancy Category',
                'verbose_name_plural': 'Pregnancy Categorys',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Drug Name')),
                ('side_effects', models.CharField(blank=True, max_length=500, verbose_name='Side Effects')),
                ('generic_name', models.CharField(blank=True, max_length=500, verbose_name='Generic Name')),
                ('drug_classes', models.CharField(blank=True, max_length=500, verbose_name='Drug Classes')),
                ('brand_names', models.CharField(blank=True, max_length=500, verbose_name='Brand Names')),
                ('activity', models.IntegerField(blank=True, verbose_name='activity')),
                ('rx_otc', models.CharField(blank=True, max_length=100, verbose_name='rx_otc')),
                ('alcohol', models.BooleanField(blank=True, default=False, verbose_name='Alcohol')),
                ('related_drugs', models.CharField(blank=True, max_length=50, verbose_name='Related Drugs')),
                ('medical_condition_description', models.TextField(blank=True, verbose_name='Medical Condition Description')),
                ('rating', models.IntegerField(blank=True, verbose_name='Rating')),
                ('no_of_reviews', models.IntegerField(blank=True, verbose_name='Number Of Reviews')),
                ('drug_link', models.URLField(blank=True, verbose_name='Drug Link')),
                ('medical_condition_url', models.URLField(blank=True, verbose_name='Medical Condition URL')),
                ('csa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='details.csa', verbose_name='CSA')),
                ('medical_condition', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='details.medicalcondition', verbose_name='Medical Condition')),
                ('pregnancy_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='details.pregnancycategory', verbose_name='Pregnancy Category')),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
            },
        ),
    ]
