# Generated by Django 4.1.7 on 2023-04-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='csa',
            field=models.TextField(blank=True, verbose_name='CSA'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='medical_condition',
            field=models.TextField(blank=True, verbose_name='MedicalCondition'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='pregnancy_category',
            field=models.TextField(blank=True, verbose_name='Pregnancy Category'),
        ),
        migrations.DeleteModel(
            name='CSA',
        ),
        migrations.DeleteModel(
            name='MedicalCondition',
        ),
        migrations.DeleteModel(
            name='PregnancyCategory',
        ),
    ]
