# Generated by Django 4.1.7 on 2023-04-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_alter_drug_csa_alter_drug_medical_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='brand_names',
            field=models.TextField(blank=True, max_length=500, verbose_name='Brand Names'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='csa',
            field=models.CharField(blank=True, max_length=50, verbose_name='CSA'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_classes',
            field=models.CharField(blank=True, max_length=150, verbose_name='Drug Classes'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Drug Link'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='generic_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Generic Name'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='medical_condition_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Medical Condition URL'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='pregnancy_category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pregnancy Category'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='rating',
            field=models.FloatField(blank=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='related_drugs',
            field=models.TextField(blank=True, max_length=500, verbose_name='Related Drugs'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='rx_otc',
            field=models.CharField(blank=True, max_length=50, verbose_name='rx_otc'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='side_effects',
            field=models.CharField(blank=True, max_length=150, verbose_name='Side Effects'),
        ),
    ]
