# Generated by Django 4.1.7 on 2023-04-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_alter_drug_brand_names_alter_drug_csa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='medical_condition',
            field=models.CharField(blank=True, max_length=50, verbose_name='MedicalCondition'),
        ),
    ]
