# Generated by Django 4.1.7 on 2023-05-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_alter_drug_activity_alter_drug_side_effects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='alcohol',
            field=models.CharField(blank=True, default='False', max_length=50, verbose_name='Alcohol'),
        ),
    ]
