# Generated by Django 4.1.7 on 2023-05-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_alter_drug_alcohol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='no_of_reviews',
            field=models.CharField(blank=True, max_length=50, verbose_name='Number Of Reviews'),
        ),
    ]
