# Generated by Django 4.1.7 on 2023-05-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_alter_drug_no_of_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='rating',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rating'),
        ),
    ]
